-- 05_demo_queries.sql
-- Analytics queries that demonstrate value from the star schema.
-- All table names are fully qualified (FINFLOW.ANALYTICS.*) to avoid context errors.

-- Query 1: Monthly transaction volume and total amount
SELECT
    d.YEAR,
    d.MONTH,
    d.MONTH_NAME,
    COUNT(*)            AS TRANSACTION_COUNT,
    SUM(f.AMOUNT)       AS TOTAL_AMOUNT,
    ROUND(AVG(f.AMOUNT), 2) AS AVG_AMOUNT
FROM FINFLOW.ANALYTICS.FCT_TRANSACTIONS f
JOIN FINFLOW.ANALYTICS.DIM_DATE d ON f.TRANSACTION_DATE = d.DATE_KEY
GROUP BY d.YEAR, d.MONTH, d.MONTH_NAME
ORDER BY d.YEAR, d.MONTH;

-- Query 2: Top 10 accounts by total transaction amount
SELECT
    a.ACCOUNT_KEY,
    a.FREQUENCY,
    dist.DISTRICT_NAME,
    COUNT(*)            AS NUM_TRANSACTIONS,
    SUM(f.AMOUNT)       AS TOTAL_AMOUNT,
    ROUND(AVG(f.BALANCE), 2) AS AVG_BALANCE
FROM FINFLOW.ANALYTICS.FCT_TRANSACTIONS f
JOIN FINFLOW.ANALYTICS.DIM_ACCOUNT a ON f.ACCOUNT_KEY = a.ACCOUNT_KEY
JOIN FINFLOW.ANALYTICS.DIM_DISTRICT dist ON a.DISTRICT_ID = dist.DISTRICT_KEY
GROUP BY a.ACCOUNT_KEY, a.FREQUENCY, dist.DISTRICT_NAME
ORDER BY TOTAL_AMOUNT DESC
LIMIT 10;

-- Query 3: Transaction volume by region
SELECT
    dist.REGION,
    COUNT(*)            AS TRANSACTION_COUNT,
    SUM(f.AMOUNT)       AS TOTAL_AMOUNT,
    ROUND(AVG(dist.AVG_SALARY), 0) AS REGION_AVG_SALARY
FROM FINFLOW.ANALYTICS.FCT_TRANSACTIONS f
JOIN FINFLOW.ANALYTICS.DIM_ACCOUNT a ON f.ACCOUNT_KEY = a.ACCOUNT_KEY
JOIN FINFLOW.ANALYTICS.DIM_DISTRICT dist ON a.DISTRICT_ID = dist.DISTRICT_KEY
GROUP BY dist.REGION
ORDER BY TOTAL_AMOUNT DESC;

-- Query 4: Transaction type breakdown (Czech labels: PRIJEM=credit, VYDAJ=debit)
SELECT
    f.TYPE,
    f.OPERATION,
    COUNT(*)            AS TRANSACTION_COUNT,
    SUM(f.AMOUNT)       AS TOTAL_AMOUNT,
    ROUND(AVG(f.AMOUNT), 2) AS AVG_AMOUNT
FROM FINFLOW.ANALYTICS.FCT_TRANSACTIONS f
GROUP BY f.TYPE, f.OPERATION
ORDER BY TRANSACTION_COUNT DESC;

-- Query 5: Year-over-year growth in transaction count
SELECT
    d.YEAR,
    COUNT(*) AS TRANSACTION_COUNT,
    LAG(COUNT(*)) OVER (ORDER BY d.YEAR) AS PREV_YEAR_COUNT,
    ROUND(
        (COUNT(*) - LAG(COUNT(*)) OVER (ORDER BY d.YEAR))
        / NULLIF(LAG(COUNT(*)) OVER (ORDER BY d.YEAR), 0) * 100,
        2
    ) AS YOY_GROWTH_PCT
FROM FINFLOW.ANALYTICS.FCT_TRANSACTIONS f
JOIN FINFLOW.ANALYTICS.DIM_DATE d ON f.TRANSACTION_DATE = d.DATE_KEY
GROUP BY d.YEAR
ORDER BY d.YEAR;

-- Query 6: Gender demographics and transaction patterns
SELECT
    c.GENDER,
    COUNT(DISTINCT c.CUSTOMER_KEY)  AS NUM_CUSTOMERS,
    COUNT(f.TRANSACTION_KEY)        AS TOTAL_TRANSACTIONS,
    SUM(f.AMOUNT)                   AS TOTAL_AMOUNT,
    ROUND(AVG(f.AMOUNT), 2)        AS AVG_TRANSACTION_AMOUNT
FROM FINFLOW.ANALYTICS.DIM_CUSTOMER c
JOIN FINFLOW.RAW.DISP dp ON c.CUSTOMER_KEY = TRY_TO_NUMBER(dp.CLIENT_ID)
JOIN FINFLOW.ANALYTICS.DIM_ACCOUNT a ON TRY_TO_NUMBER(dp.ACCOUNT_ID) = a.ACCOUNT_KEY
JOIN FINFLOW.ANALYTICS.FCT_TRANSACTIONS f ON a.ACCOUNT_KEY = f.ACCOUNT_KEY
WHERE TRIM(dp.TYPE) = 'OWNER'
GROUP BY c.GENDER
ORDER BY TOTAL_AMOUNT DESC;
